### ISSUE TITLE
Code thoughts

### ISSUE THREAD

**Issue by feilipu** [RalphBacon/244-RTOS-for-Arduino#1]
The Arduino `delay()` function is very  dangerous, as it [burns cycles while counting time](https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/wiring.c#L106).<br>__EDIT__: See comment below on [release 10.4.6-3](https://github.com/feilipu/Arduino_FreeRTOS_Library/releases/tag/10.4.6-3).

Tasks in FreeRTOS should be in Run State only when they are doing something useful. Otherwise they should be moved to Blocked State, by using a FreeRTOS delay function. See [State Table](https://www.freertos.org/RTOS-task-states.html) here.

In a RTOS `delay()` is detrimental as it ensures only the highest priority Task running `delay()` will ever get CPU time scheduled, and lower priority Tasks will NEVER get run. The RTOS becomes just a round-robin system, with one priority level and Tasks at that priority sharing CPU time. 

The `vTaskDelay()` and `vTaskDelayUntil()` functions should be used as they put the Task to sleep by Blocking for the right number of Ticks or milliseconds, with 0 processor overhead.

Turning off the Idle Task Hook `configUSE_IDLE_HOOK=0`, doesn't stop the Idle Task from being created, and run. It just stops the library providing the support for the Arduino `loop()` function. In this case `loop()` will never be run. 

As you're burning all the CPU capacity using multiple Arduino `delay()` functions, the lowest priority Idle Task (and hence also the Arduino `loop()`) will never be run.

Is there a specific reason to create a `myloop()` Task? If you're leaving Arduino `loop()` empty (as you should), then why create another empty `myloop()` Task to do nothing (particularly when it is just burning CPU by running the `delay()` function)?

Thanks again for an informative and well made video. 😄 👍

Oh and one more note. IIRC, I've noted that the Idle Task shall never be delayed or Blocked. This will mess up the [Scheduler](https://www.freertos.org/single-core-amp-smp-rtos-scheduling.html). Since the Idle Task is running the Arduino `loop()` putting a delay of any type in `loop()` will do bad things, specifically the Real Time will be broken at least, if nothing else.

**Comment by RalphBacon** [comment]
Thanks for your comment, Phillip. It made me rework the sketch and I've uploaded an alternative approach based on your recommendations. It all works very well. The reason I used 'delay' in an RTOS environment is because the ESP32 implementation converts that (it's a macro, as you doubtless know) to vTaskDelay.

Many thanks for the library too. It was fascinating seeing the tasks run on my humble Arduino UNO. I have a Mega2560 that I might try it on too (it might prevent the continual fear of memory exhaustion).

Back to your question on "why have a loop"?

On the ESP32, which I've used extensively over the past year or more, the loop (task) runs just as you might expect it to, at priority 1. As far as I know it's got nothing to do with the idle task. I use the loop (task) as I might on a non-RTOS processor, for the majority of my code, albeit controlled via the milliseconds approach I showed in #BB5 (https://youtu.be/hwEo49yyU88) - perhaps I should give up that approach and use more tasks! 😲

On the Arduino RTOS, _by default_, I would also prefer this loop to _not_ be part of the idle task (which, IIRC, we can specify via the configUSE_IDLE_HOOK definition), and just run normally (albeit as a task).

Anyway, it's all been a bit of an eye-opener for me, and I think others will benefit from having a play too. 👍🏻

**Comment by feilipu** [comment]
Yes the ESP32 uses FreeRTOS much more extensively. It is baked under the core presented to Arduino.

For Microchip (nee AVR) ATmega, I've just shimmed FreeRTOS in, using some hooks provided, with minimal changes (and without needing a specific nonstandard core). Very light touch.

I've always suggested users get going with the examples, and consider their own customisation when building larger projects.

Generally the Arduino Uno RAM can support only about 3 Tasks. Beyond that an Arduino Mega is useful.

If `loop()` is not being used some RAM can be recovered by reducing `configMINIMAL_STACK_SIZE` to 85 Bytes. The default setting for 192 Bytes is assuming some use of `loop()` as a fail safe. Yes we're saving only 107 Bytes (from 2048 Bytes in the Uno), but it is worthwhile.

I should also mention Floessie has a C++ wrapper library ([frt](https://github.com/Floessie/frt)) which also implements static RAM allocation. Worth a follow up look, if you're into C++.

👍

**Comment by feilipu** [comment]
So, I had a look around the Internet, and found that __everyone__ who is using `Arduino_FreeRTOS_Library` in tutorials is using `delay()`, and not realising the problem. So rather than being the "Old man yells at Cloud", I've added a [definition for `delay()`](https://github.com/feilipu/Arduino_FreeRTOS_Library/issues/113) to `vTaskDelay()` to [release 10.4.6-3](https://github.com/feilipu/Arduino_FreeRTOS_Library/releases/tag/10.4.6-3).

I've no Arduino to hand currently, so it would be good to test it by seeing if [your initial sketch](https://github.com/RalphBacon/244-RTOS-for-Arduino/blob/main/Arduino%20-%20RTOS/Arduino%20-%20RTOS.ino) works when the two tasks are created with different priorities. 🙏 

__EDIT__ Did the testing with [Blink_AnalogRead](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/master/examples/Blink_AnalogRead/Blink_AnalogRead.ino). The two tasks have different priorities, so if `delay()` wasn't properly redefined then the Blink (the lower priority Task) wouldn't work. It does, so we're good.
